# Generated by Django 5.2.7 on 2025-10-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del rol, debe ser único.', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del rol.')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo del usuario.', max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], default='cliente', help_text='Rol del usuario.', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
