# Generated by Django 5.2.7 on 2025-10-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default=12345678, help_text='Contraseña del usuario.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='ejemplo@gmail.com', help_text='Correo electrónico del usuario.', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
